name: Publish to Nix Registry

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  nix-publish:
    uses: pawprnt/.github/.github/workflows/nix-publish.yml@main
    with:
      pkgname: softie
      nixpkgs-repo: pawprnt/nixpkgs
    secrets:
      NIX_GITHUB_TOKEN: ${{ secrets.NIX_GITHUB_TOKEN }}
